### PR TITLE
Update package.json. Add Windows support

### PR DESCRIPTION
**Pull request by ayarushin**
## Description

- Update package.json
  - Add `cross-env` for using `NODE_ENV=` (it returned an error when you tried to exec on Window)
  - Update dependencies version to exact

## Motivation and Context
- The project should work well in all OS.
- The exact version of the dependency saves us from unexpected errors.

## How Has This Been Tested?
Clone repo to the windows machine, run: `npm install && npm run lint` or `npm install && npm test`

### CODE REVIEW

**Comment by antonioru** [comment]
@ayarushin that's a great improvement indeed, thank you very much! 

just a quick question: why you changed the lodash dependencies version from "^x.x.x" to "x.x.x" ?

**Comment by ayarushin** [comment]
поэтому я боюсьWell, at my work, I faced several issues with versions `^x.x.x` for example one of `office-ui-fabric-react:^6.*.*` version broke my app because there was an update from react 15 to react 16, but my app supported only react 15, so that why I'm afraid of not exact versions 😄

**Comment by ayarushin** [comment]
Well, at my work, I faced several issues with versions '^x.x.x' for example one of 'office-ui-fabric-react:^6.*.*' version broke my app because there was an update from react 15 to react 16, but my app supported only react 15, so that why I'm afraid of not exact versions 😄

**Comment by antonioru** [comment]
> Well, at my work, I faced several issues with versions '^x.x.x' for example one of 'office-ui-fabric-react:^6._._' version broke my app because there was an update from react 15 to react 16, but my app supported only react 15, so that why I'm afraid of not exact versions 😄

Oh I see... well, don't worry about lodash utilities, they're quite small and reliable so we can keep the `^x.x.x` format.
If, alas, in future it happens they'll break we'll build our own debounce/throttle functions since they're quite easy to implement 

Please change it back so I can quickly merge your great improvement :)

**Comment by ayarushin** [comment]
Sure, no problem :)

**Comment by ayarushin** [comment]
@antonioru done 👍

**Pull request merged**
