### PR TITLE
Add feature: useLocalStorage

### PR DESCRIPTION
**Pull request by stevenselcuk**
Signed-off-by: Steven J. Selcuk <stevenjselcuk@gmail.com>

## Description
usePersistState is classic state hook but with a persisting feature. It uses local storage to achieve this.

## Related Issue
New feature

## Motivation and Context
Easy way to using local storage (combining with state hook). More "hook" way instead of using the redux-persist thing.

## How Has This Been Tested?
 mock-local-storage has added to the dev dependency list for mocking local storage during tests.

### CODE REVIEW

**Comment by antonioru** [comment]
Hello @stevenselcuk ,

Thank you for your pull request, is absolutely lit! 
It's a very good hook and a massive improvement for the library! 
I love the fact that you committed not only to create the hook itself but the tests and the TS types also, so thank you for understanding my code and being so accurate :) 
Please feel free to give me any possible feedback to improve! 

I was just wondering if we can possibly rename the hook to `useLocalStorage` as `usePeristState` may be quite misleading for the developers, I mean: one can possibly argue that a state is - by definition - a value that **persists** during a component lifecycle (until you change it, of course), whilst renaming it as `useLocalStorage` makes clear that we are using the local storage so the value will not only be persistent during the component or app lifecycle but it will persist over time. What do you think? 

Also please notice I commented few minor fixes on the code ;) 

thank you mate

**Comment by stevenselcuk** [comment]
Of course, we can rename it 🙌 It seems more accurate and perfectly fits with other hook's naming strategy. 
I'd like to thank you too for this awesome library!

**Comment by antonioru** [comment]
thank you @stevenselcuk  your PR is now part of the codebase ad published to NPM :) 

thank you so much

**Comment by stevenselcuk** [comment]
> thank you @stevenselcuk your PR is now part of the codebase ad published to NPM :)
> 
> thank you so much

This is awesome 🙌 

You're welcome by the way nice to meet you.

**Pull request merged**
